### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Andrii-Holoshivskyi** [Andrii-Holoshivskyi/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by vovan98702** [comment]
<h1 class="name">Andriy Holoshivskii</h1>
<div class="job">Student</div>
<ul class="contacts">
  <li>
    <a href="https://www.facebook.com/people/Андрій-Голошівський/100021852204323" rel="author" class="facebook">
      <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M448 56.7v398.5c0 13.7-11.1 24.7-24.7 24.7H309.1V306.5h58.2l8.7-67.6h-67v-43.2c0-19.6 5.4-32.9 33.5-32.9h35.8v-60.5c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4v67.6h58.4V480H24.7C11.1 480 0 468.9 0 455.3V56.7C0 43.1 11.1 32 24.7 32h398.5c13.7 0 24.8 11.1 24.8 24.7z"/></svg>
      <span>Andrii Holoshivskyi</span>
    </a>
  </li>
  <li>
    <a href="tel:+380937821530" rel="author" class="phone">
      <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M272 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h224c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM160 480c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32z"></path></svg>
      <span>+38 (093) 7821530</span>
    </a>
  </li>
</ul>
