### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Andrii-Holoshivskyi** [Andrii-Holoshivskyi/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by vovan98702** [comment]
<h3>Experience</h3>
<h6>Recent</h6>
<ul class="timeline">
  <li>
  <p><em>23<sup>th</sup> November 1999 – Now</em></p>
  <p>Have no real experience :D</p>
</li>
</ul>
