### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Andrii-Holoshivskyi** [Andrii-Holoshivskyi/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vovan98702** [comment]
<section>
  <h3>Languages</h3>
  <p class="tags small"><a href="/uk-ua" hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a> <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
</section>
<section>
  <h3>Skills</h3>
  <p class="tags small">HTML CSS JS JQUERY PHOTOSHOP DELPHI MYSQL JAVA C++ </p>
</section>
<section>
  <h3>Character</h3>
  <p class="tags small">EXPLORER STRAIGHTFORWARD <a href="https://www.16personalities.com/entp-personality" rel="external">DEBATER</a> DEVOTED PEDANTIC AGNOSTIC CONTENTIOUS PROCRASTINATOR RELEVANT EMPATHETIC CONFIDENT CONSISTENT CHALLENGING</p>
</section>
<section>
  <h3>Likes&#x1f603;</h3>
  <p class="tags small">HUMOUR PATIENCE CATS COMEDIES LIGHTNOVELS SUN FREEDOME MYSTERIES</p>
</section>
<section>
  <h3>Dislikes&#x1f61e;</h3>
  <p class="tags small"><span class="nowrap">OWN BAD HABITS</span> POLITICS RACISM ASS-KISSERS VODKA INCOMPETENCE ARROGANCE ENVY GOLF <button id="chartreuse" class="color chartreuse">CHARTREUSE</button> INSECTS METRO PREJUDICE REALITY-SHOWS JŪRMALA</p>
</section>
<section>
  <h3>Wants&#x1f97a;</h3>
  <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">TO OWN MY SCHEDULE</span><span class="tag">TO READ MORE</span><span class="tag">TO BECOME IMMORTAL</span></p>
</section>
<section>
  <h3>Education</h3>
  <ul class="timeline">
    <li>
      <div><em>11<sup>st</sup> December 2018 &ndash; 21<sup>th</sup> February 2019</em></div>
      <div><strong>Certificates of Java Advanced Course Completion</strong> at <a href="https://itca.if.ua/" rel="external"><strong>IT-Cluster Academy</strong></a></div>
    </li>
    <li>
      <div><em>1<sup>st</sup> September 2005 &ndash; 31<sup>st</sup> March 2016</em></div>
      <div><strong>Certificate of graduation</strong> at <strong>№20 Middle School of General Education</strong></div>
    </li>
  </ul>
</section>
